name: "CI"

on:
  push:
    paths-ignore: "./ci-basics.yml"
  workflow_dispatch: ~

jobs:
  deps:
    name: "Install depedencies"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          tools: composer
      - name: "Install PHP deps"
        run: composer install --prefer-dist --no-interaction --no-progress
